version: 2

project_name: vibeusage

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vibeusage
    main: ./cmd/vibeusage
    binary: vibeusage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/joshuadavidthomas/vibeusage/internal/cli.version={{ .Tag }}

archives:
  - id: default
    ids:
      - vibeusage
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
