name: workflows

on:
  push:
    branches: [main]
    paths:
      - .github/actions/**
      - .github/dependabot.yml
      - .github/workflows/**
      - .github/zizmor.yml
      - .pre-commit-config.yaml
      - go.mod
      - mise.toml
  pull_request:
    paths:
      - .github/actions/**
      - .github/dependabot.yml
      - .github/workflows/**
      - .github/zizmor.yml
      - .pre-commit-config.yaml
      - go.mod
      - mise.toml

permissions:
  contents: read

concurrency:
  group: workflows-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        with:
          install_args: pre-commit zizmor

      - name: Check Action versions and owners
        run: pre-commit run check --all-files
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Audit workflow security
        run: pre-commit run lint --all-files
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Validate workflow syntax
        run: pre-commit run validate --all-files
